python3 ../../../prolin-xcb-client/client.py ACM0 push 1942.sna /data/app/MAINAPP/1942.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push 1942ME~1.sna /data/app/MAINAPP/1942ME~1.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push 1942Megalargodenarices.sna /data/app/MAINAPP/1942Megalargodenarices.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push 1943.sna /data/app/MAINAPP/1943.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push 1stDemo.sna /data/app/MAINAPP/1stDemo.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push 3Dcoolkm.sna /data/app/MAINAPP/3Dcoolkm.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push 48z80ful.sna /data/app/MAINAPP/48z80ful.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push 4openKM.sna /data/app/MAINAPP/4openKM.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push AceOfAce.sna /data/app/MAINAPP/AceOfAce.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push AticAtac.sna /data/app/MAINAPP/AticAtac.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push BabyInot.sna /data/app/MAINAPP/BabyInot.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push BartDemo.sna /data/app/MAINAPP/BartDemo.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push BestialW.sna /data/app/MAINAPP/BestialW.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push BlueSky.sna /data/app/MAINAPP/BlueSky.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push BountBob.sna /data/app/MAINAPP/BountBob.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push Bubble.sna /data/app/MAINAPP/Bubble.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push Bumpy.sna /data/app/MAINAPP/Bumpy.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push ConQuest.sna /data/app/MAINAPP/ConQuest.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push Cookie.sna /data/app/MAINAPP/Cookie.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push DREAMW~1.sna /data/app/MAINAPP/DREAMW~1.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push DreamWalker48.sna /data/app/MAINAPP/DreamWalker48.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push ESIDemo.sna /data/app/MAINAPP/ESIDemo.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push FlyShark.sna /data/app/MAINAPP/FlyShark.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push FnMatrix.sna /data/app/MAINAPP/FnMatrix.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push GDC.sna /data/app/MAINAPP/GDC.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push Ghosts.sna /data/app/MAINAPP/Ghosts.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push GlugGlug.sna /data/app/MAINAPP/GlugGlug.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push Humphrey.sna /data/app/MAINAPP/Humphrey.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push Hyperact.sna /data/app/MAINAPP/Hyperact.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push Karnov.sna /data/app/MAINAPP/Karnov.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push Motos.sna /data/app/MAINAPP/Motos.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push MsPacMan.sna /data/app/MAINAPP/MsPacMan.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push MusicDemo128.sna /data/app/MAINAPP/MusicDemo128.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push NiftyLif.sna /data/app/MAINAPP/NiftyLif.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push Nstar.sna /data/app/MAINAPP/Nstar.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push OrcAtack.sna /data/app/MAINAPP/OrcAtack.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push PacMan.sna /data/app/MAINAPP/PacMan.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push Packrat.sna /data/app/MAINAPP/Packrat.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push Penetrat.sna /data/app/MAINAPP/Penetrat.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push PercyPot.sna /data/app/MAINAPP/PercyPot.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push PeteJuke.sna /data/app/MAINAPP/PeteJuke.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push Pheenix.sna /data/app/MAINAPP/Pheenix.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push Pippo.sna /data/app/MAINAPP/Pippo.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push Pssst.sna /data/app/MAINAPP/Pssst.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push Seymour.sna /data/app/MAINAPP/Seymour.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push Silkworm.sna /data/app/MAINAPP/Silkworm.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push Solomons.sna /data/app/MAINAPP/Solomons.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push Targetr.sna /data/app/MAINAPP/Targetr.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push TestDri2.sna /data/app/MAINAPP/TestDri2.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push ThePunk.sna /data/app/MAINAPP/ThePunk.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push Tunnel4K.sna /data/app/MAINAPP/Tunnel4K.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push Uridium.sna /data/app/MAINAPP/Uridium.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push Wicked.sna /data/app/MAINAPP/Wicked.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push WizLair2.sna /data/app/MAINAPP/WizLair2.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push Zer0Demo.sna /data/app/MAINAPP/Zer0Demo.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push Zynaps.sna /data/app/MAINAPP/Zynaps.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push amc1.sna /data/app/MAINAPP/amc1.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push basic.sna /data/app/MAINAPP/basic.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push batman.sna /data/app/MAINAPP/batman.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push bbasic.sna /data/app/MAINAPP/bbasic.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push bombjack.sna /data/app/MAINAPP/bombjack.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push bombman.sna /data/app/MAINAPP/bombman.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push booble.sna /data/app/MAINAPP/booble.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push booty.sna /data/app/MAINAPP/booty.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push californ.sna /data/app/MAINAPP/californ.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push cobra.sna /data/app/MAINAPP/cobra.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push coloristic.sna /data/app/MAINAPP/coloristic.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push diag.sna /data/app/MAINAPP/diag.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push diashow.sna /data/app/MAINAPP/diashow.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push editorKM.sna /data/app/MAINAPP/editorKM.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push fantasy.sna /data/app/MAINAPP/fantasy.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push fire.sna /data/app/MAINAPP/fire.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push gameover.sna /data/app/MAINAPP/gameover.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push goody.sna /data/app/MAINAPP/goody.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push greenb.sna /data/app/MAINAPP/greenb.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push hhorace.sna /data/app/MAINAPP/hhorace.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push horace1.sna /data/app/MAINAPP/horace1.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push hortow.sna /data/app/MAINAPP/hortow.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push jetPac.sna /data/app/MAINAPP/jetPac.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push jetman.sna /data/app/MAINAPP/jetman.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push jsw16k.sna /data/app/MAINAPP/jsw16k.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push madmix.sna /data/app/MAINAPP/madmix.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push madmix2.sna /data/app/MAINAPP/madmix2.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push manic.sna /data/app/MAINAPP/manic.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push mouseTes.sna /data/app/MAINAPP/mouseTes.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push panic.sna /data/app/MAINAPP/panic.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push platoon.sna /data/app/MAINAPP/platoon.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push rainerbe.sna /data/app/MAINAPP/rainerbe.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push ramboIII.sna /data/app/MAINAPP/ramboIII.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push robocop.sna /data/app/MAINAPP/robocop.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push robotron.sna /data/app/MAINAPP/robotron.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push saboteu1.sna /data/app/MAINAPP/saboteu1.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push scroll.sna /data/app/MAINAPP/scroll.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push simon.sna /data/app/MAINAPP/simon.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push sipka.sna /data/app/MAINAPP/sipka.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push sppong.sna /data/app/MAINAPP/sppong.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push t1.sna /data/app/MAINAPP/t1.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push tapper.sna /data/app/MAINAPP/tapper.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push tetr.sna /data/app/MAINAPP/tetr.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push tetr2.sna /data/app/MAINAPP/tetr2.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push tetris.sna /data/app/MAINAPP/tetris.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push tstr.sna /data/app/MAINAPP/tstr.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push zaxxon.sna /data/app/MAINAPP/zaxxon.sna
python3 ../../../prolin-xcb-client/client.py ACM0 push zxum.sna /data/app/MAINAPP/zxum.sna
